### ISSUE TITLE
mocha tests not running properly on node 0.10

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-parser-js#176]
See https://travis-ci.org/shapesecurity/shift-parser-js/builds/58723528 for example.

```
$ istanbul cover node_modules/.bin/_mocha -- --inline-diffs --check-leaks --ui tdd --reporter dot --recursive test


  ․․․․․․․․․․․․․․․․․․․․․
/shift-parser-js/node_modules/mocha/lib/runner.js:576
  runnable.clearTimeout();
           ^
TypeError: Object #<Object> has no method 'clearTimeout'
    at Runner.uncaught (/Users/michael/projects/shift-parser-js/node_modules/mocha/lib/runner.js:576:12)
    at process.uncaught (/Users/michael/projects/shift-parser-js/node_modules/mocha/lib/runner.js:609:10)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:301:26)
```

**Comment by michaelficarra** [comment]
Fixed by https://github.com/shapesecurity/shift-parser-js/commit/99d58ee2a8097aba2ca7e70cad17e0b3d4c24535.
