### ISSUE TITLE
Fails to parse sequence expression without parens in for-in RHS

### ISSUE THREAD

**Issue by lydell** [shapesecurity/shift-parser-js#347]
test.js:

```js
const { parseModule } = require("shift-parser");

const input = "for (a in b, c);";
console.log(parseModule(input));
```

```
$ node test.js 
/home/lydell/test/node_modules/shift-parser/dist/parser.js:184
      throw this.createUnexpected(this.lookahead);
      ^

Error: [1:12]: Unexpected token ","
    at new JsError (/home/lydell/test/node_modules/shift-parser/dist/tokenizer.js:165:81)
    at GenericParser.createError (/home/lydell/test/node_modules/shift-parser/dist/tokenizer.js:294:14)
    at GenericParser.createUnexpected (/home/lydell/test/node_modules/shift-parser/dist/tokenizer.js:275:23)
    at GenericParser.expect (/home/lydell/test/node_modules/shift-parser/dist/parser.js:184:18)
    at GenericParser.getIteratorStatementEpilogue (/home/lydell/test/node_modules/shift-parser/dist/parser.js:830:12)
    at GenericParser.parseForStatement (/home/lydell/test/node_modules/shift-parser/dist/parser.js:799:98)
    at GenericParser.parseStatementHelper (/home/lydell/test/node_modules/shift-parser/dist/parser.js:604:23)
    at GenericParser.isolateCoverGrammar (/home/lydell/test/node_modules/shift-parser/dist/parser.js:1089:23)
    at GenericParser.parseStatement (/home/lydell/test/node_modules/shift-parser/dist/parser.js:578:23)
    at GenericParser.parseStatementListItem (/home/lydell/test/node_modules/shift-parser/dist/parser.js:570:25)
```

**Comment by michaelficarra** [comment]
Confirmed. for-of only allows AssignmentExpression, but for-in allows sequences. See [IterationStatement](https://tc39.github.io/ecma262/#prod-IterationStatement).

**Comment by bakkot** [comment]
Huh. I [explicitly disallowed this](https://github.com/shapesecurity/shift-parser-js/issues/310). Guess I misread the grammar.
